/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/auth/register": {
    post: operations["AuthController_register"];
  };
  "/api/auth/login": {
    post: operations["AuthController_login"];
  };
  "/api/products": {
    get: operations["ProductController_findAll"];
    post: operations["ProductController_create"];
  };
  "/api/products/{id}": {
    get: operations["ProductController_findOne"];
    delete: operations["ProductController_remove"];
    patch: operations["ProductController_update"];
  };
  "/api/cart": {
    get: operations["CartController_getCart"];
  };
  "/api/cart/add": {
    post: operations["CartController_addItem"];
  };
  "/api/cart/item/{id}": {
    delete: operations["CartController_removeItem"];
    patch: operations["CartController_updateItem"];
  };
  "/api/orders/checkout": {
    post: operations["OrderController_checkout"];
  };
  "/api/orders": {
    get: operations["OrderController_findAll"];
  };
  "/api/orders/{id}": {
    get: operations["OrderController_findOne"];
  };
  "/api/web-image/convert-all": {
    get: operations["WebImageController_convertAll"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AuthController_register: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_login: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  ProductController_findAll: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  ProductController_create: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  ProductController_findOne: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ProductController_remove: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ProductController_update: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CartController_getCart: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  CartController_addItem: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  CartController_removeItem: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CartController_updateItem: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  OrderController_checkout: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  OrderController_findAll: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  OrderController_findOne: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  WebImageController_convertAll: {
    responses: {
      200: {
        content: never;
      };
    };
  };
}
