export const ErrorCodes = {
  // General Errors
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Auth Domain
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Cart & Order Domain
  EMPTY_CART: 'EMPTY_CART',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  CART_ITEM_NOT_OWNED: 'CART_ITEM_NOT_OWNED',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
